name: tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Build and run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: "ubuntu-20.04"
        python-version: "3.7"

    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: test-environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          miniforge-variant: Mambaforge
      - name: Install basic dependencies
        run: |
          mamba install -q -y coverage cython=0.29.* matplotlib=3.1.* nose numpy=1.16.* pythreejs sympy=1.5.* scipy=1.3.*
      - name: Test with nose
        run: nosetests -v --with-coverage --cover-package=pydy
      - name: Test installation of PyDy
        run: python setup.py install
